/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData google = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe801, fontFamily: _kFontFam);
}
